name: CI/CD for OrderService

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      # Step 3: Authenticate using Service Account
      - name: Authenticate with service account
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 4: Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/orderservice-repo/orderservice:latest .

      # Step 6: Push Docker image
      - name: Push Docker image
        run: |
          docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/orderservice-repo/orderservice:latest

      # ✅ Step 7: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy orderservice \
            --image asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/orderservice-repo/orderservice:latest \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated \
            --service-account=cloudrun-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com \
            --set-secrets=DB_URL=DB_URL:latest,DB_USERNAME=DB_USERNAME:latest,DB_PASSWORD=DB_PASSWORD:latest,REDIS_HOST=REDIS_HOST:latest,REDIS_PORT=REDIS_PORT:latest,REDIS_USERNAME=REDIS_USERNAME:latest,REDIS_PASSWORD=REDIS_PASSWORD:latest,KAFKA_BOOTSTRAP_SERVERS=KAFKA_BOOTSTRAP_SERVERS:latest,KAFKA_SASL_USERNAME=KAFKA_SASL_USERNAME:latest,KAFKA_SASL_PASSWORD=KAFKA_SASL_PASSWORD:latest,KAFKA_TRUSTSTORE_PASSWORD=KAFKA_TRUSTSTORE_PASSWORD:latest,AWS_ACCESS_KEY=AWS_ACCESS_KEY:latest,AWS_SECRET_KEY=AWS_SECRET_KEY:latest,AWS_REGION=AWS_REGION:latest,AWS_S3_BUCKET=AWS_S3_BUCKET:latest,CLOUDINARY_CLOUD_NAME=CLOUDINARY_CLOUD_NAME:latest,CLOUDINARY_API_KEY=CLOUDINARY_API_KEY:latest,CLOUDINARY_API_SECRET=CLOUDINARY_API_SECRET:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest
