package com.OrderPaymentNotificationService.OrderPaymentNotificationService.DTO;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.util.UUID;

/**
 * Request body sent by the delivery partner to confirm COD payment collection.
 *
 * Security model:
 *  - Endpoint requires ROLE_DELIVERY JWT.
 *  - OTP was generated by the customer and shown to the delivery partner.
 *  - collectedAmountPaise must exactly match the transaction amount stored in DB;
 *    any mismatch aborts confirmation.
 */
public record CodConfirmRequest(

        @NotNull(message = "Transaction ID is required")
        UUID transactionId,

        @NotBlank(message = "OTP is required")
        @Size(min = 6, max = 6, message = "OTP must be exactly 6 digits")
        @Pattern(regexp = "^[0-9]{6}$", message = "OTP must be numeric")
        String otp,

        @NotBlank(message = "Collected amount is required")
        @Pattern(regexp = "^[0-9]+(\\.[0-9]{1,2})?$", message = "Invalid amount format")
        String collectedAmountPaise) {
}
